centos2g: #
server:
  port: 10007
spring:
  application:
    name: mall-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${centos2g}:3306/emall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: huxiaoge
    password: ZWZmMGFmMmI0MGEwMGQ4MzQ2MTU4OTAw
  redis:
    host: ${centos2g}
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  session:
    store-type: redis
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000

    cloud:
      loadbalancer:
        retry:
          enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

mybatis-plus:
  global-config:
    banner: false



