centos2g: #
centos4g: #
server:
  port: 15999
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: mall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${centos2g}:3306/emall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: huxiaoge
    password: ZWZmMGFmMmI0MGEwMGQ4MzQ2MTU4OTAw
  rabbitmq:
    host: ${centos4g}
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  session:
    store-type: redis
    redis:
      namespace: spring:sessions
  mythread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000

    cloud:
      loadbalancer:
        retry:
          enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
    banner: false

seata:
  registry:
    nacos:
      application: seata-server
      server-addr: ${centos4g}:8060
      group: SEATA_GROUP

  config:
    nacos:
      namespace: ef28588f-643e-4466-a0ef-89b47f9e8572
      server-addr: ${centos4g}:8060
      group: SEATA_GROUP

  service:
    vgroup-mapping:
      order-tx-group: default
    disable-global-transaction: false
    grouplist:
      default: ${centos4g}:8091
#  enable-auto-data-source-proxy: true
  enabled: false
  tx-service-group: order-tx-group
  enableAutoDataSourceProxy: true
#  use-jdk-proxy: true

# 支付宝设置
alipay:
  app_id: 2021000117677712
  # 商户私钥
  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC5CqGTgFP1R+5t+cPGi4enWNoJUfnjJJtv2+2FjtnG2UA6QJiXiD1VUpIXj1ml3A8CRcWBEHn8n4f9aDpTa5ivrjHM1nIJn2RTvbbU60tr+kUAvzQP/CJyZUyn9FyUkmsTpkd+MHWVf4eUIWOixJ24pQEm2znmf/HTF5DFU3K0rMts5eCUtYfmdMrXgcAHWSJ/yzUao8q/kgGPzWineydfI7m93l0sySstvt6Ni7GninKJaAn9hilhzK+SUHX0mhbTDD0rJ9q9g4dbObyRloKciTrp8opG6Kc7Xxz+Ss8OSYOLWxSW3GPt8Yv2p7i3uh3Vr2Miv/bnEbqAreVs/8S1AgMBAAECggEBAIN5h0ZLZtwfaMyhKzZWC2OfIQSAR4HZj8uRwxkjX58G27jIDuOT/Kg0C/NLelH7onpl4qgKcfJJ05D8znxZNdqVdXLqZ4powxsw78gnCqbE4uRd9nrpFfyb9zRazrENu6Dxg1ioy9MWEtnwQ1/yPXJlYwUdvO0GuWbYFpft69FswcUKR+lSe2y5/hpjt1SuE9SVT3zIe4A0rGAh5tauZr/Pym6DKy1qBxAUsm1ZDvvrxxoYJCN6by1einHikqhtrmYrWroEuVlh1L9nf+cGc5x2w86KR8/ZI2ulbGRCscLbSe55Ra1fvw1wessSYhzP5VZcA7EDm7zabSHIVvDWSwECgYEA80CeBspLAGcp7H+IGDITx4ezveBxphqgvN1p56cg0CBQeKLuShJl9Gj1JGwP4akKlsPjOTJ434f6YPhNf/eZu0Jp8GnxptMlKMvunZxwIZ6idNd9dscNeoEh4k2pjF01Rmdkfwr8ulTV/o0aXb67vmRXM0eRAJwvHhHaiveEpsECgYEAwr0UHiPiJkIn5KW8TYrV3s+k9Zz9U0Q1qXQ/K3ngx2tMbt8w6oV7QLJqgReNWSlh++D3qqWTlR2G8hnBfcw5WQJmKUEMDMsYxfyMNj+aa69uS7r0obUfoWf7y6einkqNZesMzKx2L9suc8HOPlyP8gPqn4fXoIrgnvjBLIv1rvUCgYEAkjmxxRst4twhE43GXeUchsFIh0e4icVQAriGxT5uNy51sU8gN16/8yB03KQpF9nqB59RpDx29Mhk9o3M6LQKscrGrELDhSlAGToeApjbvxoBRoOTZCdcLtwZZlSRK1OMhvn4K3aLXedJjG99/gR+D4F5+dV3kQpSOJ065nbMQwECgYAKQ2jSBdYfahEsLcf01kJbUdpBz5pSTx/85FGH+w5rtC39EepEEfDjAgQ29YTPlCzD16F17vAORdYc4FqgRKkpFcVIm1MFQZb2qE7DdSqwTjij6SCHfUJDgXV10Enzyb4WBwNPri80anrSQv6ZrssvWCF/cutcXLVl63pS3LWAGQKBgQDvZUSCnHYjyIv91ShaYf5Vl4up+APbRfYxE8n8yPKM7u1GDrlcGgRwBXS481/LdCSqcF64314eYM3EJwSpHoz5Z+OWMoGW77qtpNL9LNPetgaKCWv2iDccRzt7tHBRZE9pDSLM8VS0bRn6ZuqtCTHUASQmh+Nt+aWpnezaUjP2Fw==
  # 支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmIF/jyOSFeyqIZtijj+eVNsP+cfS6nlohj6DpVi7Ej+tBSNzEB9cGKDmX3OZiTpNflQhkyr9T78Qe/b3R0bdCrZlLS80jiRUqHTK2bDGf5sKKwR2BdEbNg4PO1mpeFKYPgzr2i5COLzxb0JJUMJs6mcfrcxJ9g6gl1PxysDow3owUXKve79z7CHOg/bHNvEGdEqOo6TnzyhDPu0kv07lupcuCdXX9Gw2M1I35inbPfKRdZtX2yfXdyntP506WGTNguOE+7rsHhy+/Ai4oP3GtTf57RxAcfov9nR0b0myW/4y4mndYnSWfbQvnK30tyCKNP4e01ea0DSDmWGL1osUwIDAQAB
  # 支付成功的异步回调地址
  notify_url: http://o407z85684.qicp.vip/payed/notify
  # 支付成功后的跳转地址
  return_url: http://member.emall.com/myOrder.html
  # 加密算法
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

