centos2g: #
centos4g: #
server:
  port: 15999
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: mall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${centos2g}:3306/emall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: huxiaoge
    password: ZWZmMGFmMmI0MGEwMGQ4MzQ2MTU4OTAw
  rabbitmq:
    host: ${centos4g}
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  session:
    store-type: redis
    redis:
      namespace: spring:sessions
  mythread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000

    cloud:
      loadbalancer:
        retry:
          enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
    banner: false

seata:
  registry:
    nacos:
      application: seata-server
      server-addr: ${centos4g}:8060
      group: SEATA_GROUP

  config:
    nacos:
      namespace: ef28588f-643e-4466-a0ef-89b47f9e8572
      server-addr: ${centos4g}:8060
      group: SEATA_GROUP

  service:
    vgroup-mapping:
      order-tx-group: default
    disable-global-transaction: false
    grouplist:
      default: ${centos4g}:8091
#  enable-auto-data-source-proxy: true
  enabled: false
  tx-service-group: order-tx-group
  enableAutoDataSourceProxy: true
#  use-jdk-proxy: true



