server:
  port: 15999
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: mall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://#:3306/emall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: huxiaoge
    password: ZWZmMGFmMmI0MGEwMGQ4MzQ2MTU4OTAw
  rabbitmq:
    host: #
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  session:
    store-type: redis
    redis:
      namespace: spring:sessions
  mythread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
    banner: false
