server:
  port: 8866

spring:
  application:
    name: mall-gateway

  cloud:
    gateway:
      routes:
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: mall-ware
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: mall-fast
          uri: lb://mall-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /mall-fast/$\{segment}

        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Host=auth.emall.com

        - id: mall-search-web
          uri: lb://mall-search
          predicates:
            - Host=search.emall.com

        - id: mall-cart-web
          uri: lb://mall-cart
          predicates:
            - Host=cart.emall.com

        - id: mall-product-web
          uri: lb://mall-product
          predicates:
            - Host=**.emall.com, emall.com







