server:
  port: 8866

spring:
  application:
    name: mall-gateway

  cloud:
    gateway:
      routes:
        - id: mall-fast
          uri: lb://mall-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/()


    nacos:
      discovery:
        server-addr: #:8060


