centos2g: #
server:
  port: 10001
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: mall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${centos2g}:3306/emall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: huxiaoge
    password: ZWZmMGFmMmI0MGEwMGQ4MzQ2MTU4OTAw
    hikari:
      max-lifetime: 50000
  redis:
    host: ${centos2g}
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: cache_
      use-key-prefix: true
      cache-null-values: true
  thymeleaf:
    cache: true

  mythread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

  session:
    store-type: redis
    redis:
      namespace: spring:session

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
    banner: false
