centos2g: #
server:
  port: 9999
  servlet:
    context-path: /mall-fast

spring:
  redis:
    database: 0
    host: ${centos2g}
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${centos2g}:3306/emall_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: huxiaoge
    password: ZWZmMGFmMmI0MGEwMGQ4MzQ2MTU4OTAw
    hikari:
      max-lifetime: 50000

  application:
    name: mall-fast


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
    banner: false

