centos2g: #
centos4g: #

server:
  port: 9998
spring:
  application:
    name: mall-seckill
  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  rabbitmq:
    host: ${centos4g}
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000

    cloud:
      loadbalancer:
        retry:
          enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


