centos2g: #

server:
  port: 9998
spring:
  application:
    name: mall-seckill
  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10



