centos2g: #
centos4g: #
server:
  port: 10002

spring:
  application:
    name: mall-ware

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${centos2g}:3306/emall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: huxiaoge
    password: ZWZmMGFmMmI0MGEwMGQ4MzQ2MTU4OTAw

  rabbitmq:
    host: ${centos4g}
    port: 5672
    # 开启手动确认
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:/mapper/**/*.xml

seata:
  registry:
    nacos:
      application: seata-server
      server-addr: ${centos4g}:8060
      group: SEATA_GROUP

  config:
    nacos:
      namespace: ef28588f-643e-4466-a0ef-89b47f9e8572
      server-addr: ${centos4g}:8060
      group: SEATA_GROUP

  service:
    vgroup-mapping:
      order-tx-group: default
    disable-global-transaction: false
    grouplist:
      default: ${centos4g}:8091
  enableAutoDataSourceProxy: true
  enabled: false
  tx-service-group: order-tx-group
#  use-jdk-proxy: true
