centos2g:
server:
  port: 13344
spring:
  application:
    name: mall-cart
  thymeleaf:
    cache: false
  redis:
    host: ${centos2g}
    port: 6379
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  session:
    store-type: redis
    redis:
      namespace: spring:sessions
  mythread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
