centos4g: #
server:
  port: 9201

elastic:
  host: ${centos4g}
  port: 9200

spring:
  application:
    name: mall-search
  thymeleaf:
    cache: true

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000

  cloud:
    loadbalancer:
      retry:
        enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout : 60000


